### ISSUE TITLE
Does not appear to work

### ISSUE THREAD

**Issue by cmurrayis** [H1B0B0/Kick-Viewerbot#1]
Tested for educational purposes and could not get it to increase viewers even with 1000 or 100000 threads. I suspect the method of reporting viewers has been updated.

**Comment by douglascxbx** [comment]
same here.

**Comment by H1B0B0** [comment]
Hello, thank you for the feedback. I will review it in my free time. Unfortunately, I won't be able to do it right away, but I promise to work on it soon.

**Comment by H1B0B0** [comment]
You can add my discord: h1b0b0.

**Comment by cmurrayis** [comment]
Hi,

I did a couple of weeks back ;)

**Comment by H1B0B0** [comment]
Send me a message.

**Comment by H1B0B0** [comment]
@cmurrayis Maybe I deleted it by mistake. Could you please send me a new invitation?

**Comment by H1B0B0** [comment]
Hello, the problem is fixed. Thank you for waiting.
